language: swift
os: osx
osx_image: xcode10.1

branches:
  only: [master]

env:
  - PLATFORM='macOS'
  - PLATFORM='iOS'

cache:
  directories:
    - /usr/local/lib/mint

script: make bootstrap test

notifications:
  email: false
